const mongoose = require('mongoose');

const projectHoursPlanSchema = new mongoose.Schema({
  teamspaceId:                { type: mongoose.Schema.Types.ObjectId, ref: 'Teamspace', required: true, index: true },
  projectId:                  { type: mongoose.Schema.Types.ObjectId, ref: 'Project',   required: true, index: true },
  title:                      { type: String, required: true },
  periodMonth:                { type: String, required: true },     // 'YYYY-MM' (or 'YYYY-MM..YYYY-MM' for multi-month)
  periodStart:                { type: Date,   required: true },     // first calendar day of the period
  periodEnd:                  { type: Date,   required: true },     // last calendar day of the period
  // periodKind drives how the period is interpreted:
  //   single-month   — periodMonth = 'YYYY-MM'; one calendar month (default, legacy)
  //   multi-month    — periodMonth = 'YYYY-MM..YYYY-MM'; T&M-style multi-month bucket
  //   sprint         — periodStart/End taken from Sprint.start/end; sprintId set
  //   services-child — auto-generated by a services parent; one per month
  //   maintenance    — recurring monthly bucket (parentPlanId = template on first month)
  periodKind:                 { type: String, enum: ['single-month','multi-month','sprint','services-child','maintenance'], default: 'single-month', index: true },
  sprintId:                   { type: mongoose.Schema.Types.ObjectId, ref: 'Sprint', index: true },
  parentPlanId:               { type: mongoose.Schema.Types.ObjectId, ref: 'ProjectHoursPlan', index: true },
  recurrence: {
    active:        { type: Boolean, default: false },
    monthlyHours:  { type: Number,  default: 0 },
    nextRunOn:     { type: Date },
  },
  // 'awaiting_finance' = owner has approved, but the plan exceeds the org-wide
  // countersign threshold so a Super Admin must also approve before the budget
  // is released. Allocations and time logging stay blocked in this state.
  status:                     { type: String, enum: ['draft','pending','awaiting_finance','approved','rejected'], default: 'draft', index: true },

  // Hours
  totalPlannedHours:          { type: Number, default: 0 },
  billablePlannedHours:       { type: Number, default: 0 },
  nonBillablePlannedHours:    { type: Number, default: 0 },

  // Cost (every hour costs the company)
  totalCostCents:             { type: Number, default: 0 },
  billableCostCents:          { type: Number, default: 0 },
  nonBillableCostCents:       { type: Number, default: 0 },

  // Revenue (only billable hours generate revenue)
  totalRevenueCents:          { type: Number, default: 0 },

  // Actuals (recomputed from approved TimeEntries)
  totalActualHours:           { type: Number, default: 0 },
  billableActualHours:        { type: Number, default: 0 },
  nonBillableActualHours:     { type: Number, default: 0 },
  totalActualCostCents:       { type: Number, default: 0 },
  billableActualCostCents:    { type: Number, default: 0 },
  nonBillableActualCostCents: { type: Number, default: 0 },
  totalActualRevenueCents:    { type: Number, default: 0 },

  // P&L (derived, cached for fast dashboards)
  plannedProfitCents:         { type: Number, default: 0 },
  actualProfitCents:          { type: Number, default: 0 },
  plannedMarginPct:           { type: Number, default: 0 },
  actualMarginPct:            { type: Number, default: 0 },
  variancePctCached:          { type: Number, default: 0 },

  ragStatus:                  { type: String, enum: ['green','amber','red','grey'], default: 'grey' },

  submittedAt:                { type: Date },
  submittedBy:                { type: String },
  approvedAt:                 { type: Date },
  approvedBy:                 { type: String },
  rejectedAt:                 { type: Date },
  rejectedBy:                 { type: String },
  rejectionReason:            { type: String },
  attachmentId:               { type: String },                     // optional original Excel upload (file name in /uploads)

  // ── Scope % vs. project overall budget ────────────────────────────────
  // scopePercentage  — PM's declared share of project scope this plan covers
  //                    (0-100). e.g. "this plan delivers 30% of the project".
  // The system computes expected cost = project.overallBudget × scopePercentage/100
  // and flags variance between plan.totalCost and expected. Helps catch
  // "you're using 50% of budget but only delivering 30% of scope" early.
  scopePercentage:            { type: Number, default: 0, min: 0, max: 100 },

  // Two-step "Finance counter-sign" — applied to plans whose cost or revenue
  // exceeds FINANCE_COUNTERSIGN_THRESHOLD_CENTS at the moment the owner approves.
  // Owner approval transitions status → 'awaiting_finance'; Super Admin then
  // counter-signs to release the budget (status → 'approved').
  requiresFinanceCountersign: { type: Boolean, default: false },
  financeCountersignThresholdCents: { type: Number, default: 0 }, // snapshot at submit time
  ownerApprovedAt:            { type: Date },
  ownerApprovedBy:            { type: String },
  financeCountersignedAt:     { type: Date },
  financeCountersignedBy:     { type: String },

  createdBy:                  { type: String },
  updatedBy:                  { type: String },
}, { timestamps: true });

// Non-unique compound index for fast lookup by (project, month).
// Multiple plans per project+month are allowed (e.g., supplementary budget approvals).
projectHoursPlanSchema.index({ teamspaceId: 1, projectId: 1, periodMonth: 1 });

module.exports = mongoose.model('ProjectHoursPlan', projectHoursPlanSchema);
